name: Go Build Test
on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Build
    steps:
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
          
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .
